FROM ubuntu:16.04
RUN apt-get update && \
    apt-get install -y python3-pip tesseract-ocr
WORKDIR /app
COPY *.ttf /usr/share/fonts/truetype/
COPY *.traineddata /usr/share/tesseract-ocr/tessdata/
COPY *.wordlist .
COPY dist/*.whl .
RUN pip3 install *.whl && \
    rm *.whl
